DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;

CREATE TABLE KUNDE (
    KUNDENID       INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	DATE,
	STRASSE         VARCHAR(50),
	HAUSNR			VARCHAR(6),			
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50)
    );

CREATE TABLE ZUTAT(
    ZUTATENID			INTEGER NOT NULL,
    BEZEICHNUNG         VARCHAR(50),
    EINHEIT        	    VARCHAR (25),
    NETTOPREIS          DECIMAL(10,2),
    BESTAND             INTEGER,
    LIEFERANT			INTEGER,
	KALORIEN			INTEGER,
	KOHLENHYDRATE		DECIMAL (10,2),
	PROTEIN				DECIMAL(10,2)
);

CREATE TABLE BESTELLUNG (
    BESTELLID        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENID         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLID)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLID       INTEGER NOT NULL,
    ZUTATENID       INTEGER,
    MENGE     		INTEGER
);

CREATE TABLE REZEPTZUTAT (
    ZUTATENID       INTEGER,
    REZEPTID        INTEGER,
    MENGE           DECIMAL (10,2)
);

CREATE TABLE REZEPTBESTELLUNG (
    BESTELLID       INTEGER,
    REZEPTID        INTEGER
);

CREATE TABLE REZEPT (
    REZEPTID                INTEGER NOT NULL,
    REZEPTNAME              VARCHAR(50)
);

CREATE TABLE ERNAEHRUNGSKATEGORIEN (
    ERNAEHRUNGSID          INTEGER NOT NULL,
    BEZEICHNUNG             VARCHAR(50),
    PRIMARY KEY (ERNAEHRUNGSID)
);

CREATE TABLE UNVERTRAEGLICHKEITEN (
    UNVERTRAEGLICHKEITSID  INTEGER NOT NULL,
    BEZEICHNUNG             VARCHAR(50),
    PRIMARY KEY (UNVERTRAEGLICHKEITSID)
);

CREATE TABLE ERNAERUNGREZEPT (
    ERNAEHRUNGSID          INTEGER,
    REZEPTID                INTEGER
);

CREATE TABLE UNVERTRAEGLICHKEITREZEPT (
    UNVERTRAEGLICHKEITSID  INTEGER,
    REZEPTID                INTEGER
);

CREATE TABLE LIEFERANT (
    LIEFERANTENID   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR			VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON			VARCHAR(25),
    EMAIL           VARCHAR(50)
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/


ALTER TABLE ZUTAT ADD PRIMARY KEY (ZUTATENID);
ALTER TABLE KUNDE ADD PRIMARY KEY (KUNDENID);
ALTER TABLE REZEPT ADD PRIMARY KEY (REZEPTID);
ALTER TABLE LIEFERANT ADD PRIMARY KEY (LIEFERANTENID);
ALTER TABLE BESTELLUNGZUTAT ADD PRIMARY KEY (BESTELLID,ZUTATENID);
ALTER TABLE REZEPTZUTAT ADD PRIMARY KEY (REZEPTID,ZUTATENID);
ALTER TABLE REZEPTBESTELLUNG ADD PRIMARY KEY (REZEPTID,BESTELLID);
ALTER TABLE ERNAERUNGREZEPT ADD PRIMARY KEY (ERNAEHRUNGSID,REZEPTID);
ALTER TABLE UNVERTRAEGLICHKEITREZEPT ADD PRIMARY KEY (UNVERTRAEGLICHKEITSID,REZEPTID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ZUTAT ADD FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENID);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (BESTELLID) REFERENCES BESTELLUNG (BESTELLID);
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENID) REFERENCES KUNDE (KUNDENID);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT (ZUTATENID);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (REZEPTID) REFERENCES REZEPT (REZEPTID);
ALTER TABLE REZEPTZUTAT ADD FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT (ZUTATENID);
ALTER TABLE REZEPTBESTELLUNG ADD FOREIGN KEY (BESTELLID) REFERENCES BESTELLUNG (BESTELLID);
ALTER TABLE REZEPTBESTELLUNG ADD FOREIGN KEY (REZEPTID) REFERENCES REZEPT (REZEPTID);
ALTER TABLE ERNAERUNGREZEPT ADD FOREIGN KEY (ERNAEHRUNGSID) REFERENCES ERNAEHRUNGSKATEGORIEN (ERNAEHRUNGSID);
ALTER TABLE ERNAERUNGREZEPT ADD FOREIGN KEY (REZEPTID) REFERENCES REZEPT (REZEPTID);
ALTER TABLE UNVERTRAEGLICHKEITREZEPT ADD FOREIGN KEY (UNVERTRAEGLICHKEITSID) REFERENCES UNVERTRAEGLICHKEITEN (UNVERTRAEGLICHKEITSID);
ALTER TABLE UNVERTRAEGLICHKEITREZEPT ADD FOREIGN KEY (REZEPTID) REFERENCES REZEPT (REZEPTID);