UPDATE KUNDE 
SET NACHNAME = 'DSGVO', VORNAME = 'DSGVO', GEBURTSDATUM = '0000-00-00', STRASSE = 'DSGVO',
HAUSNR = 'DSGVO', PLZ = 'DSGVO', ORT = 'DSGVO', TELEFON = 'DSGVO', EMAIL = 'DSGVO'
WHERE KUNDENID = '2002';